fix Windows binaries for cross-compilation
Cross-compiling for Windows from Linux fails, at least on Ubuntu 16.06
with GCC 4.8 (e.g. with xgo). The error is the following:

```
../../vendor/gopkg.in/bblfsh/client-go.v2/tools/lib/libxml2.a(error.o):error.c:(.text+0x242): undefined reference to `__imp___acrt_iob_func'
../../vendor/gopkg.in/bblfsh/client-go.v2/tools/lib/libxml2.a(parserInternals.o):parserInternals.c:(.text+0x5d1): undefined reference to `__imp___acrt_iob_func'
../../vendor/gopkg.in/bblfsh/client-go.v2/tools/lib/libxml2.a(relaxng.o):relaxng.c:(.text+0x1de7): undefined reference to `__imp___acrt_iob_func'
../../vendor/gopkg.in/bblfsh/client-go.v2/tools/lib/libxml2.a(relaxng.o):relaxng.c:(.text+0xb407): undefined reference to `__imp___acrt_iob_func'
../../vendor/gopkg.in/bblfsh/client-go.v2/tools/lib/libxml2.a(relaxng.o):relaxng.c:(.text+0xb44e): undefined reference to `__imp___acrt_iob_func'
../../vendor/gopkg.in/bblfsh/client-go.v2/tools/lib/libxml2.a(relaxng.o):relaxng.c:(.text+0xb4a7): more undefined references to `__imp___acrt_iob_func' follow
collect2: error: ld returned 1 exit status
```

This seems to be a problem with libxml2 compiled with mingw's gcc 7.3. Compiling it with gcc 6.3 solves the problem.

Turns out that AppVeyor have both versions pre-installed in the Visual Studio 2015 image. So, for mingw builds, we switch to Visual Studio 2015 image plus mingw 6.3.0. msvc builds still use Visual Studio 2017 image.

Signed-off-by: Santiago M. Mola <santi@mola.io>